services:
  quizzbackend:
    build: .
    container_name: quizzbackend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - /home/test/certs:/certs:ro
    networks:
      - iqnet

networks:
  iqnet: {}