networks:
  iqnet: {}

services:

  quizzbackend:
    build: ./src/mon-backend
    container_name: quizzbackend
    ports:
      - "3000:3000"
    environment:
      - SSL_KEY_PATH=/certs/key.pem
      - SSL_CERT_PATH=/certs/cert.pem
      - NODE_ENV=production
      - PORT=3000
    env_file:
      - ./src/mon-backend/.env   # contient DB_HOST, DB_PORT, etc.
    networks:
      - iqnet
    restart: unless-stopped

  quizzfrontend:
    build: ../iq-quest-hub
    container_name: quizzfrontend
    ports:
      - "8085:8085"
    volumes:
      - /home/test/certs:/certs:ro  # chemin Linux de tes certs sur la VM
    depends_on:
      - quizzbackend
    networks:
      - iqnet
    restart: unless-stopped